Replace `mkinitrd` with `dracut` on Fedora and RHEL
rear/rear pull request #2825
Opened 2022-06-21 15:58 UTC by lzaoral

#### Pull Request Details:

* Type: **Bug Fix**

* Impact: **High**

* Reference to related issue (URL): https://bugzilla.redhat.com/show_bug.cgi?id=2096900

* How was this pull request tested?

RHEL 9 VM without this patch that failed to regenerate the `initrd` and same VM with this patch that regenerated the `initrd` successfully.

* Brief description of the changes in this pull request:

For a long time, `mkinitrd` was a wrapper script around `dracut` in Fedora and RHEL that maintained backwards compatibility with the real (but rather obsolete) `mkinitrd`.

Dracut 054 removed the `mkinitrd` wrapper script [1] so now we have to execute `dracut` directly.  Fortunately, ReaR did not use almost anything from `mkinitrd`'s interface (with the exception of `--with`) so the transition is quite straightforward.

Without this patch the initrd regeneration in the finalize stage of recovery fails on RHEL 9 and Fedora 33 or newer.

[1] https://github.com/dracutdevs/dracut/pull/1285

2022-06-22 06:57 UTC, jsmeix requested changes
I don't see anything regarding backward compatibility.
So I assume the changes will not work with older Red Hat versions.
See the section "Maintain backward compatibility" in
https://github.com/rear/rear/wiki/Coding-Style
Accordingly I cannot approve it as is.
At least it must be tested and documented whether or not
those changes still work with older Red Hat versions.

2022-06-22 08:17 UTC, pcahyna commented
@jsmeix I checked that `dracut` exists in RHEL 6 (the oldest release that ReaR cares about) and that even there `mkinitrd` was a shell script that invokes `dracut` internally. Of course this does not guarantee that it will work properly, but at least the chances are quite high.

2022-06-22 10:25 UTC, jsmeix commented
@pcahyna 
when the changes work sufficiently backward compatible
for what Red Hat needs we should include it in ReaR 2.7
so feel free to merge it as you like.

2022-06-22 13:46 UTC, lzaoral commented
@jsmeix, Sorry, I should have already mentioned that in the commit message.  As @pcahyna already mentioned, RHEL 6 was the first release that used `dracut` to generate initrds.  That said I've also tested this change on RHEL 7 and RHEL 8 without any dracut related regressions spotted.

2022-06-22 15:13 UTC, jsmeix approved these changes

2022-06-23 14:03 UTC, jsmeix commented
@pcahyna 
is there a reason why you do not merge it?

2022-07-04 13:44 UTC, jsmeix commented
@pcahyna
is there a reason why you do not merge it?

Could or should perhaps I "just merge" it?

2022-07-04 13:48 UTC, merged

2022-07-04 13:50 UTC, jsmeix commented
@pcahyna 
thank you