Support creation of EFI system partition on systems with older `parted`
rear/rear pull request #2830
Opened 2022-06-24 14:01 UTC by lzaoral

This PR is based on #2829 so let's keep it a draft until that's resolved and properly rebased.

##### Pull Request Details:

* Type: **Bug Fix**

* Impact: **Normal**

* Reference to related issue (URL): https://github.com/rear/rear/pull/2828#issuecomment-1164134153

* How was this pull request tested? not much, I'll test it thoroughly after #2829 is merged

* Brief description of the changes in this pull request:

`parted` 3.2 added the support for `esp` keyword.  Thus, `parted` 3.1 on RHEL 7 does not support it yet so try a fallback that sets the corresponding partition type using `sgdisk`.

2022-06-24 14:10 UTC, jsmeix commented
@lzaoral 
what I see in
https://github.com/rear/rear/pull/2830/files
does not look right to me.
It seems to also contain changes from my
https://github.com/rear/rear/pull/2829
that should not be included here.
I guess your pull request here was not based
on plain master code but on
https://github.com/rear/rear/pull/2829

2022-06-24 14:11 UTC, jsmeix requested changes
See
https://github.com/rear/rear/pull/2830#issuecomment-1165615188

2022-06-24 14:11 UTC, jsmeix commented
Now I leave...

2022-06-24 14:20 UTC, lzaoral commented
@jsmeix Yes, I know. That's expected and that's what I meant by 
> This PR is based on https://github.com/rear/rear/pull/2829 so let's keep it a draft until that's resolved and properly rebased.

in the header. Without it, the code was otherwise more involved for such a small change.

2022-07-01 11:19 UTC, jsmeix commented
@lzaoral 
I merged https://github.com/rear/rear/pull/2829 right now
so could you please rebase your pull request here
so that I can also merge it.

2022-07-01 21:50 UTC, pcahyna commented
@jsmeix, done

2022-07-04 13:45 UTC, jsmeix commented
@rear/wiki-contributors 
if there are no objections
I would like to merge it tomorrow afternoon.

2022-07-05 05:11 UTC, lzaoral commented
@pcahyna thanks for the rebase!

@jsmeix sorry for a longer response time. I have tested this PR only by comparing the outputs of gdisk on RHEL 7 and 8 (there still some small differences, though not anymore in the type of the EFI system partition) but I haven't tested if such layout is still bootable. There are national holidays in Czechia right now so will get to it on Thursday.

2022-07-07 18:58 UTC, lzaoral commented
Tested on RHEL 7 with BIOS and EFI (both hybrid and native disk layouts) and the rescue USB booted fine and the restore was successful.

2022-07-12 05:59 UTC, jsmeix commented
@lzaoral 
thank you for verifying on RHEL7.

2022-07-12 05:59 UTC, jsmeix commented
@rear/contributors 
if there are no objections
I would like to merge it today afternoon.

2022-07-12 11:45 UTC, merged