Storing and reading Self Encrypted Disk (SED) password from TPM
rear/rear pull request #3355
Opened 2024-12-04 14:11 UTC by prolez

#### Relax-and-Recover (ReaR) Pull Request Template

Please fill in the following items before submitting a new pull request:

##### Pull Request Details:

* Type: Enhancement

* Impact: Low

* Reference to related issue (URL): https://github.com/rear/rear/issues/3074

* How was this pull request tested? on production environment

* Description of the changes in this pull request: Add functions in unlock-opal-disks to offer storing password in TPM2

2024-12-19 15:58 UTC, prolez commented
@jsmeix 
Thank you for your feedback!

I based this development on the OPAL_PBA_TKN functionality, which is only used in the mkopalpba function.
The mkrescue function does not utilize this functionality, so I am unable to debug it like this.
The password is managed the same way (like OPAL_PBA_TKN) in the PBA, which resides in the shadow MBR.
I believe this implementation is correct and safe, but I could be mistaken.

2025-01-11 05:47 UTC, paulalesius commented
> @jsmeix Thank you for your feedback!
> 
> I based this development on the OPAL_PBA_TKN functionality, which is only used in the mkopalpba function. The mkrescue function does not utilize this functionality, so I am unable to debug it like this. The password is managed the same way (like OPAL_PBA_TKN) in the PBA, which resides in the shadow MBR. I believe this implementation is correct and safe, but I could be mistaken.

The way Secure Boot works in combination with TPM2 is it attempts to measure different parts of the hardware and software during boot, the measured hashes are stored in registers called "PCR registers". The correct way to use TPM is to create a sealed and encrypted object in TPM which will only be released when the specified PCR measurments are the expected measurments to prove that the hardware or software has not been tampered with.

From what I can see in the patch, this uses the TPM as a database and it can be fetched regardless of whether the hardware/firmware/boot software has been tampered with (For instance had UEFI configuration changed to disable Secure Boot or had the firmware/hardware modified in any way).

I'm not an expert in TPM2 but it seems to require the creation of keys first:
> tpm2_createprimary -C o -c primary.ctx

And then you can seal the token in TPM based on PCR measruments:
> echo -n "<your_token>" | tpm2_create -C primary.ctx -u key.pub -r key.priv -L "sha256:0,2,7" -a "fixedtpm|fixedparent|noda|adminwithpolicy" -i -

And load the sealed and encrypted object into TPM:
> tpm2_load -C primary.ctx -u key.pub -r key.priv -c sealedobject.ctx

The "sha256:0,2,7" specifies that the token is sealed based on PCR0 PCR2 and PCR7, and if these TPM registers contain unexpected hashes then the system has been modified/tampered with and the token will not be released from TPM to unlock in PBA. It is also necessary to allow the user to configure which PCR values to bind to, as different computers have different security requirements and configurations.

I'm unsure if TPM2 works with multiple primary keys but you can check how systemd-cryptenroll stores the LUKS2 password in TPM to enable automatic authentication during boot, bound by PCR measurments:
> systemd-cryptenroll --tpm2-device=auto --tpm2-pcrs=7+8 /dev/$DEVICE

https://github.com/systemd/systemd/blob/main/src/cryptenroll/cryptenroll-tpm2.c

A new TPM2 context is created or reused if already present (tpm2_create, but it uses an abstraction layer Tpm2Context instead of calling the shell commands):
> r = tpm2_context_new_or_warn(device, &tpm2_context);

Without sealing the key, it defeats the purpose of using TPM when the keys are released regardless of whether the system has been modified.

2025-01-28 21:21 UTC, schlomo requested changes
Thanks for working on this, much appreciated!

TBH, all of this is quite cryptic for me to understand it like this, but all of the OPAL code is like that, too...

Could you also update https://github.com/rear/rear/blob/master/doc/user-guide/13-tcg-opal-support.adoc together with this change to explain how to use it and what the requirements are?

Please also note with which distros you managed to test this, ideally we cover RHEL/SLES/Debian.

2025-01-28 21:21 UTC, schlomo commented on usr/share/rear/prep/OPALPBA/Linux-i386/001_configure_workflow.sh
> +    REQUIRED_PROGS+=( 'tpm2_nvundefine' 'tpm2_nvdefine' 'tpm2_nvread' 'tpm2_nvwrite' )
```suggestion
    REQUIRED_PROGS+=( tpm2_nvundefine tpm2_nvdefine tpm2_nvread tpm2_nvwrite )
```

2025-01-28 21:21 UTC, schlomo commented on usr/share/rear/prep/OPALPBA/Linux-i386/001_configure_workflow.sh
> +    LIBS+=( /usr/lib/x86_64-linux-gnu/libtss2-*.so* )
Is this the only path where this library can be? Can we anyhow generalize that a bit?

2025-01-28 21:21 UTC, schlomo commented on usr/share/rear/conf/default.conf
> +OPAL_PBA_TPMNVINDEX="0x1500116"
Is this a special value or just something that you happen to use? Why should this be the default (maybe silly question as I don't really know what it means)

2025-02-26 09:42 UTC, prolez commented on usr/share/rear/conf/default.conf
> +OPAL_PBA_TPMNVINDEX="0x1500116"
This is indeed a random value that I came across in the various sources I reviewed during my development. I kept this value configurable for exactly this reason.

2025-02-26 09:56 UTC, prolez commented on usr/share/rear/prep/OPALPBA/Linux-i386/001_configure_workflow.sh
> +    REQUIRED_PROGS+=( 'tpm2_nvundefine' 'tpm2_nvdefine' 'tpm2_nvread' 'tpm2_nvwrite' )
Ok! I did as on rear/usr/share/rear/prep/OPALPBA/Linux-i386/001_configure_workflow.sh so it might be necessary to modify it too

2025-02-26 10:03 UTC, prolez commented on usr/share/rear/prep/OPALPBA/Linux-i386/001_configure_workflow.sh
> +    LIBS+=( /usr/lib/x86_64-linux-gnu/libtss2-*.so* )
Again I used the same mechanism as @jsmeix for OPAL_PBA_TKNPATH. I haven't looked on all distributions but it seems to be the default location.

2025-05-09 08:53 UTC, gdha approved these changes

2025-05-09 08:56 UTC, gdha commented
> Thanks for working on this, much appreciated!
> 
> TBH, all of this is quite cryptic for me to understand it like this, but all of the OPAL code is like that, too...
> 
> Could you also update https://github.com/rear/rear/blob/master/doc/user-guide/13-tcg-opal-support.adoc together with this change to explain how to use it and what the requirements are?
> 
> Please also note with which distros you managed to test this, ideally we cover RHEL/SLES/Debian.

@prolez This seems the last open item for you (updating the document). Once that is done we can merge this PR - thanks for your contribution.

2025-06-12 15:24 UTC, prolez commented
@gdha Sorry for the response time... I wanted to position myself in the same area as the AuthToken container management, but I couldn't locate it. Should we consider adding a new section for : Storing and reading Self Encrypted Disk (SED) password automatically on boot? (either from an external device or from the TPM)

2025-06-13 06:41 UTC, gdha commented
> @gdha Sorry for the response time... I wanted to position myself in the same area as the AuthToken container management, but I couldn't locate it. Should we consider adding a new section for : Storing and reading Self Encrypted Disk (SED) password automatically on boot? (either from an external device or from the TPM)

@prolez Sounds good to me - thanks!

2025-06-16 14:10 UTC, gdha approved these changes

2025-06-17 08:47 UTC, gdha commented
@rear/contributors  Would like to merge this PR upcoming Friday if there are no updates or comments?

2025-06-20 09:54 UTC, merged

2025-06-20 09:55 UTC, gdha commented
@prolez  The PR has been merged. Thank you very much for your contribution.